#!/usr/bin/env bun
// mirai/src/codegen/entities.ts
import { resolve } from "node:path";

type RawState = { entity_id: string; attributes: { options?: string } };

const isStringArray = (x: unknown): x is string[] =>
	Array.isArray(x) && x.every((y) => typeof y === "string");

const url = process.env.HA_HOST;
const token = process.env.HA_TOKEN;
const outAtg = process.argv[2] ?? "generated/entities.ts";

if (!url || !token) {
	console.error("HA_HOST and HA_TOKEN must be set");
	process.exit(1);
}

const res = await fetch(`${url}/api/states`, {
	headers: { Authorization: `Bearer ${token}` },
});

if (!res.ok) {
	throw new Error(`Failed to fetch entities: ${res.status}`);
}

const states = (await res.json()) as RawState[];
const ids = states.map((s) => s.entity_id).sort();

const stateLines = states
	.flatMap((s) =>
		isStringArray(s.attributes.options)
			? [
					`\t\t\t${JSON.stringify(s.entity_id)}: ${s.attributes.options.map((o) => JSON.stringify(o)).join(" | ")};`,
				]
			: [],
	)
	.sort()
	.join("\n");

const out = `// AUTO-GENERATED by src/codegen/entities.ts. Do not edit
export {};

declare module "mirai" {
    interface Register {
        entityId:
${ids.map((id) => `\t\t| "${id}"`).join("\n")};
        entityState: {
${stateLines}
        }
    }
}
`;

const outPath = resolve(process.cwd(), outAtg);
await Bun.write(outPath, out);

console.log(`wrote ${ids.length} entities -> ${outPath}`);
