#!/usr/bin/env bun
// mirai/src/codegen/entities.ts
import { resolve } from "node:path";

const url = process.env.HA_HOST;
const token = process.env.HA_TOKEN;
const outAtg = process.argv[2] ?? "generated/entities.ts";

if (!url || !token) {
	console.error("HA_HOST and HA_TOKEN must be set");
	process.exit(1);
}

const res = await fetch(`${url}/api/states`, {
	headers: { Authorization: `Bearer ${token}` },
});

if (!res.ok) {
	throw new Error(`Failed to fetch entities: ${res.status}`);
}

const states = (await res.json()) as { entity_id: string }[];
const ids = states.map((s) => s.entity_id);

const out = `// AUTO-GENERATED by src/codegen/entities.ts. Do not edit
export {};

declare module "mirai" {
    interface Register {
        entityId:
${ids.map((id) => `\t\t| "${id}"`).join("\n")};
    }
}
`;

const outPath = resolve(process.cwd(), outAtg);
await Bun.write(outPath, out);

console.log(`wrote ${ids.length} entities -> ${outPath}`);
