#!/usr/bin/env bun
// mirai/src/codegen/services.ts
import { resolve } from "node:path";

const url = process.env.HA_HOST;
const token = process.env.HA_TOKEN;
const outArg = process.argv[2] ?? "generated/services.ts";

if (!url || !token) {
	console.error("HA_HOST and HA_TOKEN must be set");
	process.exit(1);
}

const res = await fetch(`${url}/api/services`, {
	headers: { Authorization: `Bearer ${token}` },
});

if (!res.ok) {
	throw new Error(`Failed to fetch services: ${res.status}`);
}

const domains = (await res.json()) as {
	domain: string;
	services: Record<string, unknown>;
}[];

const lines = domains
	.sort((a, b) => a.domain.localeCompare(b.domain))
	.map(({ domain, services }) => {
		const names = Object.keys(services)
			.sort()
			.map((s) => `"${s}"`)
			.join(" | ");
		return `\t\t\t${JSON.stringify(domain)}: ${names || "never"};`;
	})
	.join("\n");

const out = `// AUTO-GENERATED by src/codegen/services.ts. Do not edit
export {};

declare module "mirai" {
    interface Register {
        services: {
${lines}
        };
    }
}
`;

const outPath = resolve(process.cwd(), outArg);
await Bun.write(outPath, out);

console.log(`wrote ${domains.length} domains -> ${outPath}`);
