#!/usr/bin/env bun
// mirai/src/codegen/serviceData.ts
import { resolve } from "node:path";

type SelectorConfig = {
	options?: (string | { value: string })[];
	multiple?: boolean;
} | null;

type Field = {
	required?: boolean;
	selector?: Record<string, SelectorConfig>;
	fields?: Record<string, Field>;
};
type Domain = {
	domain: string;
	services: Record<string, { fields?: Record<string, Field> }>;
};

const url = process.env.HA_HOST;
const token = process.env.HA_TOKEN;
const outArg = process.argv[2] ?? "generated/serviceData.ts";

if (!url || !token) {
	console.error("HA_HOST and HA_TOKEN must be set");
	process.exit(1);
}

const res = await fetch(`${url}/api/services`, {
	headers: { Authorization: `Bearer ${token}` },
});

if (!res.ok) {
	throw new Error(`Failed to fetch services: ${res.status}`);
}

const domains = (await res.json()) as Domain[];

const selectorToTs = (sel: Record<string, SelectorConfig> = {}) => {
	const [kind, cfg] = Object.entries(sel)[0] ?? ["", {}];
	switch (kind) {
		case "number":
		case "color_temp":
			return "number";
		case "boolean":
			return "boolean";
		case "text":
		case "time":
		case "date":
		case "datetime":
		case "icon":
		case "theme":
			return "string";
		case "select":
			const options: unknown[] = cfg?.options ?? [];
			const lits = options.map((o) =>
				JSON.stringify(
					typeof o === "string" ? o : (o as { value: string }).value,
				),
			);
			const union = lits.length ? lits.join(" | ") : "string";
			return cfg?.multiple ? `(${union})[]` : union;
		case "color_rgb":
			return "[number, number, number]";
		case "entity":
			return "EntityId | EntityId[]";
		default:
			return "unknown";
	}
};

const flatten = (fields: Record<string, Field> = {}): [string, Field][] =>
	Object.entries(fields).flatMap(([k, f]) =>
		f.fields ? flatten(f.fields) : [[k, f]],
	);

const key = (s: string) =>
	/^[a-z_][a-z0-9_]*$/i.test(s) ? s : JSON.stringify(s);

const body = domains
	.sort((a, b) => a.domain.localeCompare(b.domain))
	.map(({ domain, services }) => {
		const svcs = Object.entries(services)
			.sort(([a], [b]) => a.localeCompare(b))
			.map(([name, svc]) => {
				const props = flatten(svc.fields)
					.map(
						([f, def]) =>
							`${key(f)}${def.required ? "" : "?"}: ${selectorToTs(def.selector)};`,
					)
					.join(" ");
				return `\t\t\t\t${key(name)}: {${props}};`;
			})
			.join("\n");
		return `\t\t\t${key(domain)}: {\n${svcs}\n\t\t\t};`;
	})
	.join("\n");

const out = `// AUTO-GENERATED by src/codegen/serviceData.ts. Do not edit
import type { EntityId } from "mirai";

export {};

declare module "mirai" {
    interface Register {
        serviceData: {
${body}
        };
    }
}
`;

const outPath = resolve(process.cwd(), outArg);
await Bun.write(outPath, out);

console.log(`wrote ${domains.length} domains -> ${outPath}`);
